# Generated by Django 3.2.7 on 2024-01-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('key', models.IntegerField(editable=False, null=True)),
                ('abbr', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'z_arole_city',
            },
        ),
        migrations.CreateModel(
            name='DragEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=206)),
                ('details', models.TextField(blank=True, default='')),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('links', models.CharField(default='', editable=False, max_length=2000)),
                ('direction', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('hosts', models.CharField(max_length=100000, null=True)),
                ('banner', models.ImageField(null=True, upload_to='event_pics')),
                ('raw_date', models.IntegerField(default=0)),
                ('event_date', models.CharField(default='', max_length=1000)),
                ('event_time', models.CharField(default='', max_length=1000)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'z_arole_event',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_events', models.ManyToManyField(to='event.DragEvent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'z_arole_bookmark',
            },
        ),
    ]
