# Generated by Django 3.2.7 on 2023-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragevent',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='banner',
            field=models.ImageField(null=True, upload_to='event_pics'),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='hosts',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='links',
            field=models.CharField(default='', editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='dragevent',
            name='venue',
            field=models.CharField(default='', max_length=200),
        ),
    ]
