# Generated by Django 3.2.7 on 2024-01-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='z_arole_bookmark',
        ),
        migrations.AlterModelTable(
            name='city',
            table='z_arole_city',
        ),
        migrations.AlterModelTable(
            name='dragevent',
            table='z_arole_event',
        ),
    ]
