# Generated by Django 3.2.7 on 2023-01-26 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20230126_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragevent',
            name='address',
        ),
        migrations.AlterField(
            model_name='dragevent',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
