# Generated by Django 3.2.7 on 2023-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230126_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragevent',
            name='direction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
