# Generated by Django 3.2.7 on 2023-01-28 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20230126_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragevent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
