# Generated by Django 3.2.7 on 2023-02-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230128_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragevent',
            name='event_date',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='event_time',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dragevent',
            name='raw_date',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
