# Generated by Django 3.2.7 on 2023-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20230203_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragevent',
            name='raw_date',
            field=models.IntegerField(default=0),
        ),
    ]
