# Generated by Django 3.2.7 on 2023-02-03 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_dragevent_raw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragevent',
            name='raw_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
