# Generated by Django 3.2.7 on 2023-03-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_dragevent_raw_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('abbr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
