# Generated by Django 3.2.7 on 2023-03-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_city_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragevent',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dragevent',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dragevent',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dragevent',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
