# Generated by Django 3.2.7 on 2023-04-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
