# Generated by Django 3.2.7 on 2024-01-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction_completed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dragprofile',
            table='z_arole_branches',
        ),
        migrations.AlterModelTable(
            name='followmanager',
            table='z_arole_follow_manager',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='z_arole_transactions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='z_arole_users',
        ),
    ]
