# Generated by Django 3.2.7 on 2023-01-01 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dragprofile_followmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragprofile',
            old_name='approval',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='user',
            name='resetter',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='followmanager',
            name='followers',
            field=models.ManyToManyField(editable=False, related_name='user_followers', related_query_name='user_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followmanager',
            name='following',
            field=models.ManyToManyField(editable=False, related_name='followed_users', related_query_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
