# Generated by Django 3.2.7 on 2023-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230101_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
