# Generated by Django 3.2.7 on 2023-01-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230120_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragprofile',
            name='links',
            field=models.CharField(editable=False, max_length=1000, null=True),
        ),
    ]
