# Generated by Django 3.2.7 on 2023-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_dragprofile_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragprofile',
            name='links',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
