# Generated by Django 3.2.7 on 2023-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_dragprofile_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragprofile',
            name='facebook',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='instagram',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='tiktok',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='tip_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='twitter',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='website_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='youtube',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
