# Generated by Django 3.2.7 on 2023-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230228_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
