# Generated by Django 3.2.7 on 2023-04-22 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20230302_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('branch_name', models.CharField(max_length=1000, null=True)),
                ('branch_location', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('branch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dragprofile')),
                ('payer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
