# Generated by Django 3.2.7 on 2023-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20230422_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragprofile',
            name='branch_code',
            field=models.CharField(default='0', max_length=12, null=True),
        ),
    ]
