# Generated by Django 3.2.7 on 2023-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_dragprofile_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_code',
            field=models.IntegerField(blank=True, default=1234, editable=False, null=True),
        ),
    ]
