# Generated by Django 3.2.7 on 2023-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20230424_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragprofile',
            name='branch_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_branch',
            field=models.BooleanField(default=False),
        ),
    ]
