# Generated by Django 3.2.7 on 2023-04-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20230424_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragprofile',
            name='branch_location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dragprofile',
            name='branch_name',
            field=models.CharField(default='Oye Ekiti', max_length=1000, null=True),
        ),
    ]
