# Generated by Django 3.2.7 on 2023-04-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230424_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='add',
            field=models.BooleanField(default=False),
        ),
    ]
