# Generated by Django 3.2.7 on 2023-04-24 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20230424_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date made'),
        ),
    ]
