# Generated by Django 3.2.7 on 2023-04-24 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_transaction_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 11, 55, 54, 870953), verbose_name='date made'),
        ),
    ]
